---
name: Code quality
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10", "3.11-dev" ]
        continue-on-mypy-error: ["false"]
        include:
          - python-version: "3.7"
            tox-py-version: "37"
            continue-on-mypy-error: "true"
          - python-version: "3.8"
            tox-py-version: "38"
            continue-on-mypy-error: "true"
          - python-version: "3.9"
            tox-py-version: "39"
            continue-on-mypy-error: "true"
          - python-version: "3.10"
            tox-py-version: "310"
          - python-version: "3.11-dev"
            tox-py-version: "311"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip setuptools tox
      - name: Mypy
        run: |
          tox -e py${{ matrix.tox-py-version }}-mypy
          exit 1
        continue-on-error: ${{ fromJSON(matrix.contine-on-mypy-error) }}
