---
name: Prepare project
on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools
        pip install tox tox-gh-actions
    - name: Test with tox
      run: tox
